name: 1vs1
main: Minifixio\onevsone\OneVsOne
version: 1.1-DarkSight
api:
    - 3.0.0
    - 3.1.0
    - 3.0.7
    - 4.0.0
description: 'A one vs one Plugin'
permissions:
    onevsone.refarena: { description: 'Allows using /refarena', default: op }
